name: PR Test

on:
  pull_request:
    branches:
      - master
    types: [opened, synchronize, reopened]

jobs:
  lint-and-typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Run lint and typecheck
        run: npm run check
